In [3]:
from copy import deepcopy
import numpy as np
import pandas as pd
import random
from sklearn import datasets

# Ambil data iris dari sklearn
iris = datasets.load_iris()
irisData = iris.data

# Tentukan centroid
centroid_1 = irisData[0]
centroid_2 = irisData[1]
centroid_3 = irisData[2]

# Gabungkan centroid dalam listOfCentroid
listOfCentroid = []
listOfCentroid.append(centroid_1)
listOfCentroid.append(centroid_2)
listOfCentroid.append(centroid_3)

# listOfCentroid akan menghasilkan [array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2])]!
# Tidak bisa diakses, ubah lagi menggunakan np.array
listOfCentroid = np.array(listOfCentroid)


print("Centroid_1")
print(centroid_1, "\n")

print("Centroid_2")
print(centroid_2, "\n")

print("Centroid_3")
print(centroid_3, "\n")

print("List Of Centroid")
print(listOfCentroid, "\n")

# Create distance function using euclidean distance
def euclidean_dist(a, b, ax=1):
    # numpy.linalg.norm(a-b) have default orde 2, which equals to euclidean formula
    return np.linalg.norm(a - b, axis = ax)

# Simpan nilai centroid yang akan diupdate, inisialisasi dengan 0
listOfCentroid_old = np.zeros(listOfCentroid.shape)
print(listOfCentroid_old)

# Simpan centroid yang terdekat dengan titik
clusters = np.zeros(len(irisData))
print(clusters)

# Simpan error awal, iteration akan berhenti sampai error = 0
error = euclidean_dist(listOfCentroid,listOfCentroid_old,None)
print(error)

k = 3 #jumlah cluster
while error!=0:
    # Masukkan setiap titik pada cluster terdekat
    for i in range(len(irisData)):
        #cari setiap jarak terhadap centroid
        distances = euclidean_dist(irisData[i],listOfCentroid)
        print("distances pada i = " + str(i) + " : " + str(distances))
        
        #np.argmin akan mengambil indeks dengan value terkecil
        cluster = np.argmin(distances)
        print("clusters pada i = " + str(i) + " : " + str(cluster) + "\n")
        
        #masukkan dalam dalam cluster
        clusters[i] = cluster
        
    # Simpan centroid sebelumnya, berguna untuk perhitungan error 
    listOfCentroid_old = deepcopy(listOfCentroid)
    # Cari rataan untuk setiap titik pada cluster
    for i in range(k):
        points = [irisData[j] for j in range(len(irisData)) if clusters[j] == i]
        listOfCentroid[i] = np.mean(points, axis=0)
    error = euclidean_dist(listOfCentroid, listOfCentroid_old, None)

print("Centroid akhir : ")
print(listOfCentroid, "\n")

print("Hasil clustering : ")
print(clusters, "\n")

print("error : ")
print(error)

Centroid_1
[5.1 3.5 1.4 0.2] 

Centroid_2
[4.9 3.  1.4 0.2] 

Centroid_3
[4.7 3.2 1.3 0.2] 

List Of Centroid
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
10.45609869884557
distances pada i = 0 : [0.         0.53851648 0.50990195]
clusters pada i = 0 : 0

distances pada i = 1 : [0.53851648 0.         0.3       ]
clusters pada i = 1 : 1

distances pada i = 2 : [0.50990195 0.3        0.        ]
clusters pada i = 2 : 2

distances pada i = 3 : [0.64807407 0.33166248 0.24494897]
c

distances pada i = 140 : [1.98352703 2.48571197 5.24183742]
clusters pada i = 140 : 0

distances pada i = 141 : [1.63136317 2.21412827 4.8938315 ]
clusters pada i = 141 : 0

distances pada i = 142 : [1.38722006 1.49558149 4.32661378]
clusters pada i = 142 : 0

distances pada i = 143 : [2.20459116 2.72865608 5.48755165]
clusters pada i = 143 : 0

distances pada i = 144 : [2.11144494 2.64861549 5.36525399]
clusters pada i = 144 : 0

distances pada i = 145 : [1.63514689 2.14381996 4.88267302]
clusters pada i = 145 : 0

distances pada i = 146 : [1.36797141 1.58289734 4.44026468]
clusters pada i = 146 : 0

distances pada i = 147 : [1.41695105 1.8972517  4.67464587]
clusters pada i = 147 : 0

distances pada i = 148 : [1.68726151 2.17494    4.85007455]
clusters pada i = 148 : 0

distances pada i = 149 : [1.22923094 1.50823208 4.29402814]
clusters pada i = 149 : 0

distances pada i = 0 : [4.46740537 3.02955321 0.14135063]
clusters pada i = 0 : 2

distances pada i = 1 : [4.50840758 2.95201618 0

distances pada i = 146 : [0.67191504 1.31303667 4.21767471]
clusters pada i = 146 : 0

distances pada i = 147 : [0.20552142 1.63447052 4.41184542]
clusters pada i = 147 : 0

distances pada i = 148 : [0.68887353 1.93141167 4.59925864]
clusters pada i = 148 : 0

distances pada i = 149 : [0.73960008 1.24547508 4.0782815 ]
clusters pada i = 149 : 0

distances pada i = 0 : [4.64602774 3.10407677 0.14135063]
clusters pada i = 0 : 2

distances pada i = 1 : [4.68812591 3.057091   0.44763825]
clusters pada i = 1 : 2

distances pada i = 2 : [4.8533578  3.23060846 0.4171091 ]
clusters pada i = 2 : 2

distances pada i = 3 : [4.7238148  3.07661323 0.52533799]
clusters pada i = 3 : 2

distances pada i = 4 : [4.69128945 3.15333121 0.18862662]
clusters pada i = 4 : 2

distances pada i = 5 : [4.28527789 2.87088126 0.67703767]
clusters pada i = 5 : 2

distances pada i = 6 : [4.78753504 3.18436247 0.4151867 ]
clusters pada i = 6 : 2

distances pada i = 7 : [4.58434614 3.01307582 0.06618157]
clusters pada

distances pada i = 110 : [0.42745062 1.47803456 4.31225927]
clusters pada i = 110 : 0

distances pada i = 111 : [0.4067833  1.44314982 4.46533089]
clusters pada i = 111 : 0

distances pada i = 112 : [0.23405768 1.9044598  4.81086063]
clusters pada i = 112 : 0

distances pada i = 113 : [1.14769194 1.11347396 4.11543193]
clusters pada i = 113 : 1

distances pada i = 114 : [1.02769758 1.45121147 4.34736472]
clusters pada i = 114 : 0

distances pada i = 115 : [0.49160914 1.72359411 4.57650303]
clusters pada i = 115 : 0

distances pada i = 116 : [0.20330942 1.6431142  4.59734489]
clusters pada i = 116 : 0

distances pada i = 117 : [1.84912567 3.50357851 6.21697515]
clusters pada i = 117 : 0

distances pada i = 118 : [1.87945982 3.51023205 6.46018421]
clusters pada i = 118 : 0

distances pada i = 119 : [1.19710436 1.02994012 4.07258886]
clusters pada i = 119 : 1

distances pada i = 120 : [0.54956744 2.22321421 5.08121836]
clusters pada i = 120 : 0

distances pada i = 121 : [1.18538088 1.0352

distances pada i = 51 : [1.21748101 0.79749859 3.57731464]
clusters pada i = 51 : 1

distances pada i = 52 : [0.84773817 1.31711958 4.13366423]
clusters pada i = 52 : 0

distances pada i = 53 : [2.20396461 0.59666071 3.01144152]
clusters pada i = 53 : 1

distances pada i = 54 : [1.11510538 0.77640453 3.74779669]
clusters pada i = 54 : 1

distances pada i = 55 : [1.62624106 0.28845104 3.34908644]
clusters pada i = 55 : 1

distances pada i = 56 : [1.06238411 0.90022442 3.74283048]
clusters pada i = 56 : 1

distances pada i = 57 : [3.11452404 1.41463918 2.23937045]
clusters pada i = 57 : 1

distances pada i = 58 : [1.19023527 0.86994483 3.71181627]
clusters pada i = 58 : 1

distances pada i = 59 : [2.33423649 0.71833418 2.8005678 ]
clusters pada i = 59 : 1

distances pada i = 60 : [3.02328629 1.38087074 2.60022691]
clusters pada i = 60 : 1

distances pada i = 61 : [1.65053325 0.32063063 3.17042268]
clusters pada i = 61 : 1

distances pada i = 62 : [2.13631926 0.71105837 3.08317693]
cluste

distances pada i = 69 : [2.38022887 0.64594052 2.80841236]
clusters pada i = 69 : 1

distances pada i = 70 : [1.26964605 0.75582686 3.79583719]
clusters pada i = 70 : 1

distances pada i = 71 : [1.95058755 0.44154099 3.02383531]
clusters pada i = 71 : 1

distances pada i = 72 : [1.17914086 0.75687065 3.99098735]
clusters pada i = 72 : 1

distances pada i = 73 : [1.46371657 0.48254864 3.60360653]
clusters pada i = 73 : 1

distances pada i = 74 : [1.59224901 0.58011843 3.37448959]
clusters pada i = 74 : 1

distances pada i = 75 : [1.41409883 0.79087595 3.56196294]
clusters pada i = 75 : 1

distances pada i = 76 : [1.08505756 1.05075271 4.01083283]
clusters pada i = 76 : 1

distances pada i = 77 : [0.73652305 1.13780823 4.20528001]
clusters pada i = 77 : 0

distances pada i = 78 : [1.5051543  0.27980669 3.47401497]
clusters pada i = 78 : 1

distances pada i = 79 : [2.66295013 0.96238585 2.42676328]
clusters pada i = 79 : 1

distances pada i = 80 : [2.52874657 0.79728301 2.73795179]
cluste


distances pada i = 16 : [5.00219478 3.49087612 0.6542018 ]
clusters pada i = 16 : 2

distances pada i = 17 : [4.99534695 3.37762449 0.1441527 ]
clusters pada i = 17 : 2

distances pada i = 18 : [4.58840834 3.10971292 0.82436642]
clusters pada i = 18 : 2

distances pada i = 19 : [4.94411371 3.37135761 0.38933276]
clusters pada i = 19 : 2

distances pada i = 20 : [4.66670189 3.06922637 0.46344363]
clusters pada i = 20 : 2

distances pada i = 21 : [4.89580185 3.30868004 0.3286031 ]
clusters pada i = 21 : 2

distances pada i = 22 : [5.57001163 3.92319538 0.64029681]
clusters pada i = 22 : 2

distances pada i = 23 : [4.65440556 3.00463898 0.38259639]
clusters pada i = 23 : 2

distances pada i = 24 : [4.7240415  3.05369752 0.48701129]
clusters pada i = 24 : 2

distances pada i = 25 : [4.88014332 3.18551841 0.45208406]
clusters pada i = 25 : 2

distances pada i = 26 : [4.81795827 3.17190324 0.20875823]
clusters pada i = 26 : 2

distances pada i = 27 : [4.91125383 3.30315096 0.21536016]
clust

In [7]:
from copy import deepcopy
import numpy as np
import pandas as pd
import random
from sklearn import datasets

# Ambil data iris dari sklearn
iris = datasets.load_iris()
irisData = iris.data

k = 3 #jumlah cluster

# Tentukan centroid dan gabungkan centroid dalam listOfCentroid
listOfCentroid = []
rand_number = random.sample(range(0,len(irisData)-1),3)
for i in range (len(rand_number)) :
    listOfCentroid.append(irisData[rand_number[i]])

# listOfCentroid akan menghasilkan [array([xxx, xxx, xxx, xxx]), array([yyy, yyy, yyy, yyy]), array([zzz, yyy, yyy, yyy])]
# Tidak bisa diakses, ubah lagi menggunakan np.array
listOfCentroid = np.array(listOfCentroid)


print("Centroid 1")
print(listOfCentroid[0], "\n")

print("Centroid 2")
print(listOfCentroid[1], "\n")

print("Centroid 3")
print(listOfCentroid[2], "\n")

print("List Of Centroid")
print(listOfCentroid, "\n")

# Create distance function using euclidean distance
def euclidean_dist(a, b, ax=1):
    # numpy.linalg.norm(a-b) have default orde 2, which equals to euclidean formula
    return np.linalg.norm(a - b, axis=ax)

# Simpan nilai centroid yang akan diupdate, inisialisasi dengan 0
listOfCentroid_old = np.zeros(listOfCentroid.shape)

# Simpan centroid yang terdekat dengan titik
clusters = np.zeros(len(irisData))

# Simpan error awal, iteration akan berhenti sampai error = 0
error = euclidean_dist(listOfCentroid,listOfCentroid_old,None)

while error != 0:
    # Masukkan setiap titik pada cluster terdekat
    for i in range(len(irisData)):
        #cari setiap jarak terhadap centroid
        distances = euclidean_dist(irisData[i],listOfCentroid)
        print("distances pada i = " + str(i) + " : " + str(distances))
        
        #np.argmin akan mengambil indeks dengan value terkecil
        cluster = np.argmin(distances)
        print("clusters pada i = " + str(i) + " : " + str(cluster) + "\n")
        
        #masukkan dalam dalam cluster
        clusters[i] = cluster
        
    # Simpan centroid sebelumnya, berguna untuk perhitungan error 
    listOfCentroid_old = deepcopy(listOfCentroid)
    # Cari rataan untuk setiap titik pada cluster
    for i in range(k):
        points = [irisData[j] for j in range(len(irisData)) if clusters[j] == i]
        listOfCentroid[i] = np.mean(points, axis=0)
    error = euclidean_dist(listOfCentroid, listOfCentroid_old, None)

print("Centroid akhir : ")
print(listOfCentroid, "\n")

print("Hasil clustering : ")
print(clusters, "\n")

Centroid 1
[4.5 2.3 1.3 0.3] 

Centroid 2
[6.3 3.4 5.6 2.4] 

Centroid 3
[7.2 3.  5.8 1.6] 

List Of Centroid
[[4.5 2.3 1.3 0.3]
 [6.3 3.4 5.6 2.4]
 [7.2 3.  5.8 1.6]] 

distances pada i = 0 : [1.34907376 4.89182992 5.09705797]
clusters pada i = 0 : 0

distances pada i = 1 : [0.81853528 4.95983871 5.15848815]
clusters pada i = 1 : 0

distances pada i = 2 : [0.92736185 5.09215082 5.33853913]
clusters pada i = 2 : 0

distances pada i = 3 : [0.83666003 4.96286208 5.21727898]
clusters pada i = 3 : 0

distances pada i = 4 : [1.4        4.92036584 5.14975728]
clusters pada i = 4 : 0

distances pada i = 5 : [1.88148877 4.50222167 4.72228758]
clusters pada i = 5 : 0

distances pada i = 6 : [1.10905365 4.9939964  5.28866713]
clusters pada i = 6 : 0

distances pada i = 7 : [1.22882057 4.83114893 5.0447993 ]
clusters pada i = 7 : 0

distances pada i = 8 : [0.6244998  5.13225097 5.40092585]
clusters pada i = 8 : 0

distances pada i = 9 : [0.93808315 4.91426495 5.10294033]
clusters pada i = 9 : 0



clusters pada i = 73 : 1

distances pada i = 74 : [3.19165959 0.75464059 1.20996126]
clusters pada i = 74 : 1

distances pada i = 75 : [3.38434363 0.76777759 1.02978534]
clusters pada i = 75 : 1

distances pada i = 76 : [3.83068472 0.82202945 0.62512434]
clusters pada i = 76 : 2

distances pada i = 77 : [4.02532438 0.6806118  0.40378026]
clusters pada i = 77 : 2

distances pada i = 78 : [3.28364542 0.39304252 1.23058069]
clusters pada i = 78 : 1

distances pada i = 79 : [2.22709758 1.57344603 2.31038465]
clusters pada i = 79 : 1

distances pada i = 80 : [2.53333413 1.40782897 2.20508352]
clusters pada i = 80 : 1

distances pada i = 81 : [2.41810595 1.52667365 2.30367304]
clusters pada i = 81 : 1

distances pada i = 82 : [2.63417401 1.10515041 1.87491242]
clusters pada i = 82 : 1

distances pada i = 83 : [3.87870175 0.37430926 0.93281042]
clusters pada i = 83 : 1

distances pada i = 84 : [3.14451326 0.76696312 1.71289411]
clusters pada i = 84 : 1

distances pada i = 85 : [3.2936523  0.6

distances pada i = 140 : [4.90429938 1.72110445 0.4184518 ]
clusters pada i = 140 : 2

distances pada i = 141 : [4.53124181 1.50101565 0.6362747 ]
clusters pada i = 141 : 2

distances pada i = 142 : [4.06308883 0.78675293 1.29118286]
clusters pada i = 142 : 1

distances pada i = 143 : [5.14510956 1.95235551 0.37923588]
clusters pada i = 143 : 2

distances pada i = 144 : [5.02346785 1.89150568 0.55073318]
clusters pada i = 144 : 2

distances pada i = 145 : [4.53951015 1.4034451  0.58153145]
clusters pada i = 145 : 2

distances pada i = 146 : [4.14300133 0.84732711 1.07129175]
clusters pada i = 146 : 1

distances pada i = 147 : [4.34115352 1.12851958 0.6180817 ]
clusters pada i = 147 : 2

distances pada i = 148 : [4.52988352 1.45205775 0.85002224]
clusters pada i = 148 : 2

distances pada i = 149 : [4.00483343 0.7687744  1.16716811]
clusters pada i = 149 : 1

distances pada i = 0 : [0.14135063 3.41251117 5.03132789]
clusters pada i = 0 : 0

distances pada i = 1 : [0.44763825 3.38963991 5